<a href="https://colab.research.google.com/github/Kensuzuki95/EY_Assignment/blob/main/Assignment_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
pd.set_option('display.float_format', '{:.2f}'.format)

In [2]:
invoice_data = pd.read_excel('/content/drive/MyDrive/EY Recruitment Documents/invoice_data_master.xlsx')
invoice_data = invoice_data.fillna(0)
invoice_data

,file_name,store_name,invoice_number,invoice_date,product_1,quantity_1,product_2,quantity_2,product_3,quantity_3,company_name,franchise_name,company_store,address,prefecture,municipality
0,202009000096221.xlsx,お花茶屋店,202009000096221,44091,メンズ・シャンプーM,100,レディース・シャンプーL,100,0,0.00,トモズ,トモズ,トモズ_お花茶屋店,東京都葛飾区宝町２－３４－１６,東京都,東京都葛飾区
1,202006000103601.xlsx,小田急マルシェ本厚木店,202006000103601,43997,メンズ・シャンプーM,100,レディース・シャンプーL,100,0,0.00,トモズ,トモズ,トモズ_小田急マルシェ本厚木店,神奈川県厚木市中町１－１－１,神奈川県,神奈川県厚木市
2,202212000012341.xlsx,せんげん台東店,202212000012341,2022-12-09,メンズ・シャンプーM,100,レディース・シャンプーL,100,0,0.00,マツモトキヨシ,マツモトキヨシ,マツモトキヨシ_せんげん台東店,埼玉県越谷市平方南町１９－１,埼玉県,埼玉県越谷市
3,202209000096221.xlsx,お花茶屋店,202209000096221,2022-09-05,メンズ・シャンプーM,100,レディース・シャンプーL,100,0,0.00,トモズ,トモズ,トモズ_お花茶屋店,東京都葛飾区宝町２－３４－１６,東京都,東京都葛飾区
4,202006000096221.xlsx,お花茶屋店,202006000096221,43991,メンズ・シャンプーM,100,レディース・シャンプーL,100,0,0.00,トモズ,トモズ,トモズ_お花茶屋店,東京都葛飾区宝町２－３４－１６,東京都,東京都葛飾区
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4401,202004000002111.xlsx,市原店,202004000002111,2020-04-19,メンズ・シャンプーM,100,レディース・シャンプーL,100,0,0.00,イトーヨーカ堂,イトーヨーカドー,イトーヨーカ堂_市原店,千葉県市原市五井字上新道,千葉県,千葉県市原市
4402,202010000002111.xlsx,市原店,202010000002111,2020-10-17,メンズ・シャンプーM,100,レディース・シャンプーL,100,0,0.00,イトーヨーカ堂,イトーヨーカドー,イトーヨーカ堂_市原店,千葉県市原市五井字上新道,千葉県,千葉県市原市
4403,202001000002111.xlsx,市原店,202001000002111,2020-01-08,メンズ・シャンプーM,100,レディース・シャンプーL,100,0,0.00,イトーヨーカ堂,イトーヨーカドー,イトーヨーカ堂_市原店,千葉県市原市五井字上新道,千葉県,千葉県市原市
4404,202006000008681.xlsx,我孫子南口店,202006000008681,2020-06-07,メンズ・シャンプーM,100,レディース・シャンプーL,100,0,0.00,イトーヨーカ堂,イトーヨーカドー,イトーヨーカ堂_我孫子南口店,千葉県我孫子市本町３－２－２８,千葉県,千葉県我孫子市
4405,202012000008681.xlsx,我孫子南口店,202012000008681,2020-12-15,メンズ・シャンプーM,100,レディース・シャンプーL,100,0,0.00,イトーヨーカ堂,イトーヨーカドー,イトーヨーカ堂_我孫子南口店,千葉県我孫子市本町３－２－２８,千葉県,千葉県我孫子市

# Total Sales

## Tomods

In [3]:
# Filter the DataFrame based on the selected string
tomods_df = invoice_data[invoice_data['franchise_name'].str.contains('トモズ')]

# Get unique values from Column1
#unique_values = tomods_df['product_1'].unique()
#unique_values = tomods_df['product_2'].unique()
unique_values = tomods_df['product_3'].unique()

# Print the unique values
print(unique_values)

[0 'ラグジュアリ・シャンプーEx']

In [4]:
# Product prices
product_prices = {
    'メンズ・シャンプーM': 2500,
    'レディース・シャンプーL': 3000,
    'ラグジュアリ・シャンプーEx': 5000
}

# Calculate total sales for each product
tomods_df['product1_sales'] = tomods_df['quantity_1'] * product_prices['メンズ・シャンプーM']
tomods_df['product2_sales'] = tomods_df['quantity_2'] * product_prices['レディース・シャンプーL']
tomods_df['product3_sales'] = tomods_df['quantity_3'] * product_prices['ラグジュアリ・シャンプーEx']
tomods_df.head()

<ipython-input-4-0b8fb4e681bb>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tomods_df['product1_sales'] = tomods_df['quantity_1'] * product_prices['メンズ・シャンプーM']
<ipython-input-4-0b8fb4e681bb>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tomods_df['product2_sales'] = tomods_df['quantity_2'] * product_prices['レディース・シャンプーL']
<ipython-input-4-0b8fb4e681bb>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tomods_df['product3_sales'] = tomods_df['quantity_3'] * product_prices['ラグジュアリ・シャンプーEx']

,file_name,store_name,invoice_number,invoice_date,product_1,quantity_1,product_2,quantity_2,product_3,quantity_3,company_name,franchise_name,company_store,address,prefecture,municipality,product1_sales,product2_sales,product3_sales
0,202009000096221.xlsx,お花茶屋店,202009000096221,44091,メンズ・シャンプーM,100,レディース・シャンプーL,100,0,0.00,トモズ,トモズ,トモズ_お花茶屋店,東京都葛飾区宝町２－３４－１６,東京都,東京都葛飾区,250000,300000,0.00
1,202006000103601.xlsx,小田急マルシェ本厚木店,202006000103601,43997,メンズ・シャンプーM,100,レディース・シャンプーL,100,0,0.00,トモズ,トモズ,トモズ_小田急マルシェ本厚木店,神奈川県厚木市中町１－１－１,神奈川県,神奈川県厚木市,250000,300000,0.00
3,202209000096221.xlsx,お花茶屋店,202209000096221,2022-09-05,メンズ・シャンプーM,100,レディース・シャンプーL,100,0,0.00,トモズ,トモズ,トモズ_お花茶屋店,東京都葛飾区宝町２－３４－１６,東京都,東京都葛飾区,250000,300000,0.00
4,202006000096221.xlsx,お花茶屋店,202006000096221,43991,メンズ・シャンプーM,100,レディース・シャンプーL,100,0,0.00,トモズ,トモズ,トモズ_お花茶屋店,東京都葛飾区宝町２－３４－１６,東京都,東京都葛飾区,250000,300000,0.00
5,202203000096221.xlsx,お花茶屋店,202203000096221,2022-03-09,メンズ・シャンプーM,100,レディース・シャンプーL,100,0,0.00,トモズ,トモズ,トモズ_お花茶屋店,東京都葛飾区宝町２－３４－１６,東京都,東京都葛飾区,250000,300000,0.00

In [5]:
# Calculate the total sales
tomods_product1_total = tomods_df['product1_sales'].sum()
tomods_product2_total = tomods_df['product2_sales'].sum()
tomods_product3_total = tomods_df['product3_sales'].sum()
tomods_total_sales = tomods_product1_total + tomods_product2_total + tomods_product3_total
print('The total sales at Tomods is ' + str(tomods_total_sales) + ' JPY')

The total sales at Tomods is 627100000.0 JPY

## Ito-Yokado

In [6]:
# Filter the DataFrame based on the selected string
ito_yokado_df = invoice_data[invoice_data['franchise_name'].str.contains('イトーヨーカドー')]

# Get unique values from Column1
unique_values = ito_yokado_df['product_1'].unique()
#unique_values = ito_yokado_df['product_2'].unique()
#unique_values = ito_yokado_df['product_3'].unique()

# Print the unique values
print(unique_values)

['メンズ・シャンプーM']

In [7]:
# Product prices
product_prices = {
    'メンズ・シャンプーM': 2500,
    'レディース・シャンプーL': 3000,
    'ラグジュアリ・シャンプーEx': 5000
}

# Calculate total sales for each product
ito_yokado_df['product1_sales'] = ito_yokado_df['quantity_1'] * product_prices['メンズ・シャンプーM']
ito_yokado_df['product2_sales'] = ito_yokado_df['quantity_2'] * product_prices['レディース・シャンプーL']
ito_yokado_df['product3_sales'] = ito_yokado_df['quantity_3'] * product_prices['ラグジュアリ・シャンプーEx']
ito_yokado_df.head()

<ipython-input-7-8c1971772ff5>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ito_yokado_df['product1_sales'] = ito_yokado_df['quantity_1'] * product_prices['メンズ・シャンプーM']
<ipython-input-7-8c1971772ff5>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ito_yokado_df['product2_sales'] = ito_yokado_df['quantity_2'] * product_prices['レディース・シャンプーL']
<ipython-input-7-8c1971772ff5>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ito_yokado_df['product3_sales'] = ito_yokado_df['quantity_3'] * product_prices['ラグジュアリ・シャンプーEx']

,file_name,store_name,invoice_number,invoice_date,product_1,quantity_1,product_2,quantity_2,product_3,quantity_3,company_name,franchise_name,company_store,address,prefecture,municipality,product1_sales,product2_sales,product3_sales
497,202009000014461.xlsx,亀有駅前店,202009000014461,2020-09-06,メンズ・シャンプーM,100,レディース・シャンプーL,100,0,0.00,イトーヨーカ堂,イトーヨーカドー,イトーヨーカ堂_亀有駅前店,東京都葛飾区亀有３－２６－１,東京都,東京都葛飾区,250000,300000,0.00
501,202006000014461.xlsx,亀有駅前店,202006000014461,2020-06-20,メンズ・シャンプーM,100,レディース・シャンプーL,100,0,0.00,イトーヨーカ堂,イトーヨーカドー,イトーヨーカ堂_亀有駅前店,東京都葛飾区亀有３－２６－１,東京都,東京都葛飾区,250000,300000,0.00
511,202012000014461.xlsx,亀有駅前店,202012000014461,2020-12-06,メンズ・シャンプーM,100,レディース・シャンプーL,100,0,0.00,イトーヨーカ堂,イトーヨーカドー,イトーヨーカ堂_亀有駅前店,東京都葛飾区亀有３－２６－１,東京都,東京都葛飾区,250000,300000,0.00
513,202303000014461.xlsx,亀有駅前店,202303000014461,2023-03-08,メンズ・シャンプーM,100,レディース・シャンプーL,100,0,0.00,イトーヨーカ堂,イトーヨーカドー,イトーヨーカ堂_亀有駅前店,東京都葛飾区亀有３－２６－１,東京都,東京都葛飾区,250000,300000,0.00
514,202103000014461.xlsx,亀有駅前店,202103000014461,2021-03-12,メンズ・シャンプーM,100,レディース・シャンプーL,100,0,0.00,イトーヨーカ堂,イトーヨーカドー,イトーヨーカ堂_亀有駅前店,東京都葛飾区亀有３－２６－１,東京都,東京都葛飾区,250000,300000,0.00

In [8]:
# Calculate the total sales
ito_yokado_product1_total = ito_yokado_df['product1_sales'].sum()
ito_yokado_product2_total = ito_yokado_df['product2_sales'].sum()
ito_yokado_product3_total = ito_yokado_df['product3_sales'].sum()
ito_yokado_total_sales = ito_yokado_product1_total + ito_yokado_product2_total + ito_yokado_product3_total
print('The total sales at Ito-Yokado is ' + str(ito_yokado_total_sales) + ' JPY')

The total sales at Ito-Yokado is 51150000.0 JPY

## Matsumoto-Kiyoshi

In [9]:
# Filter the DataFrame based on the selected string
mastumoto_kiyoshi_df = invoice_data[invoice_data['franchise_name'].str.contains('マツモトキヨシ')]

# Get unique values from Column1
unique_values = mastumoto_kiyoshi_df['product_1'].unique()
#unique_values = mastumoto_kiyoshi_df['product_2'].unique()
#unique_values = mastumoto_kiyoshi_df['product_3'].unique()

# Print the unique values
print(unique_values)

['メンズ・シャンプーM']

In [10]:
# Product prices
product_prices = {
    'メンズ・シャンプーM': 2500,
    'レディース・シャンプーL': 3000,
    'ラグジュアリ・シャンプーEx': 5000
}

# Calculate total sales for each product
mastumoto_kiyoshi_df['product1_sales'] = mastumoto_kiyoshi_df['quantity_1'] * product_prices['メンズ・シャンプーM']
mastumoto_kiyoshi_df['product2_sales'] = mastumoto_kiyoshi_df['quantity_2'] * product_prices['レディース・シャンプーL']
mastumoto_kiyoshi_df['product3_sales'] = mastumoto_kiyoshi_df['quantity_3'] * product_prices['ラグジュアリ・シャンプーEx']
mastumoto_kiyoshi_df.head()

<ipython-input-10-843647325238>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mastumoto_kiyoshi_df['product1_sales'] = mastumoto_kiyoshi_df['quantity_1'] * product_prices['メンズ・シャンプーM']
<ipython-input-10-843647325238>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mastumoto_kiyoshi_df['product2_sales'] = mastumoto_kiyoshi_df['quantity_2'] * product_prices['レディース・シャンプーL']
<ipython-input-10-843647325238>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mastumoto_kiyoshi_df['product3_sales'] = mastumoto_kiyoshi_df['quantity_3'] * product_prices['ラグジュアリ・シャンプーEx']

,file_name,store_name,invoice_number,invoice_date,product_1,quantity_1,product_2,quantity_2,product_3,quantity_3,company_name,franchise_name,company_store,address,prefecture,municipality,product1_sales,product2_sales,product3_sales
2,202212000012341.xlsx,せんげん台東店,202212000012341,2022-12-09,メンズ・シャンプーM,100,レディース・シャンプーL,100,0,0.00,マツモトキヨシ,マツモトキヨシ,マツモトキヨシ_せんげん台東店,埼玉県越谷市平方南町１９－１,埼玉県,埼玉県越谷市,250000,300000,0.00
6,202206000012341.xlsx,せんげん台東店,202206000012341,2022-06-24,メンズ・シャンプーM,100,レディース・シャンプーL,100,0,0.00,マツモトキヨシ,マツモトキヨシ,マツモトキヨシ_せんげん台東店,埼玉県越谷市平方南町１９－１,埼玉県,埼玉県越谷市,250000,300000,0.00
12,202209000012341.xlsx,せんげん台東店,202209000012341,2022-09-08,メンズ・シャンプーM,100,レディース・シャンプーL,100,0,0.00,マツモトキヨシ,マツモトキヨシ,マツモトキヨシ_せんげん台東店,埼玉県越谷市平方南町１９－１,埼玉県,埼玉県越谷市,250000,300000,0.00
37,202303000065151.xlsx,新大久保駅前店,202303000065151,2023-03-18,メンズ・シャンプーM,100,レディース・シャンプーL,100,ラグジュアリ・シャンプーEx,100.00,マツモトキヨシ,マツモトキヨシ,マツモトキヨシ_新大久保駅前店,東京都新宿区百人町２－４－２,東京都,東京都新宿区,250000,300000,500000.00
38,202209000065151.xlsx,新大久保駅前店,202209000065151,2022-09-11,メンズ・シャンプーM,100,レディース・シャンプーL,100,ラグジュアリ・シャンプーEx,100.00,マツモトキヨシ,マツモトキヨシ,マツモトキヨシ_新大久保駅前店,東京都新宿区百人町２－４－２,東京都,東京都新宿区,250000,300000,500000.00

In [11]:
# Calculate the total sales
mastumoto_kiyoshi_product1_total = mastumoto_kiyoshi_df['product1_sales'].sum()
mastumoto_kiyoshi_product2_total = mastumoto_kiyoshi_df['product2_sales'].sum()
mastumoto_kiyoshi_product3_total = ito_yokado_df['product3_sales'].sum()
mastumoto_kiyoshi_total_sales = mastumoto_kiyoshi_product1_total + mastumoto_kiyoshi_product2_total + mastumoto_kiyoshi_product3_total
print('The total sales at Matsumoto Kiyoshi is ' + str(mastumoto_kiyoshi_total_sales) + ' JPY')

The total sales at Matsumoto Kiyoshi is 1870550000.0 JPY

## Totol Sales stas

In [12]:
# Total Sales of メンズ・シャンプーM
product1_total = tomods_product1_total + ito_yokado_product1_total + mastumoto_kiyoshi_product1_total
product1_total

1101500000

In [13]:
# Total Sales of レディース・シャンプーL
product2_total = tomods_product2_total + ito_yokado_product2_total + mastumoto_kiyoshi_product2_total
product2_total

1321800000

In [14]:
# Total Sales of ラグジュアリ・シャンプーEx
product3_total = tomods_product3_total + ito_yokado_product3_total + mastumoto_kiyoshi_product3_total
product3_total

125500000.0

In [15]:
# Total Sales of all three product combined
total_sales = tomods_total_sales + ito_yokado_total_sales + mastumoto_kiyoshi_total_sales
total_sales

2548800000.0

# Further Sales Analysis Analysis

In [16]:
# Product prices
product_prices = {
    'メンズ・シャンプーM': 2500,
    'レディース・シャンプーL': 3000,
    'ラグジュアリ・シャンプーEx': 5000
}

# Calculate total sales for each product
invoice_data['product1_sales'] = invoice_data['quantity_1'] * product_prices['メンズ・シャンプーM']
invoice_data['product2_sales'] = invoice_data['quantity_2'] * product_prices['レディース・シャンプーL']
invoice_data['product3_sales'] = invoice_data['quantity_3'] * product_prices['ラグジュアリ・シャンプーEx']
invoice_data.head(1)

,file_name,store_name,invoice_number,invoice_date,product_1,quantity_1,product_2,quantity_2,product_3,quantity_3,company_name,franchise_name,company_store,address,prefecture,municipality,product1_sales,product2_sales,product3_sales
0,202009000096221.xlsx,お花茶屋店,202009000096221,44091,メンズ・シャンプーM,100,レディース・シャンプーL,100,0,0.00,トモズ,トモズ,トモズ_お花茶屋店,東京都葛飾区宝町２－３４－１６,東京都,東京都葛飾区,250000,300000,0.00

In [17]:
# Count the total number of rows before dropping
total_rows = len(invoice_data)

# Convert invoice_date column to datetime type
invoice_data['invoice_date'] = pd.to_datetime(invoice_data['invoice_date'], errors='coerce')

# Drop rows with non-date data in invoice_date column
invoice_data_mod = invoice_data.dropna(subset=['invoice_date'])

# Count the number of rows after dropping
remaining_rows = len(invoice_data_mod)

# Count original number of invoices by franchises
total_rows_by_franchise = invoice_data.groupby('franchise_name').size()

# Count rows that remained after removing corrupted invoices by franchises
total_rows_by_franchise_mod = invoice_data_mod.groupby('franchise_name').size()

# Calculate the dropped rows by franchise
dropped_rows_by_franchise = total_rows_by_franchise.sub(total_rows_by_franchise_mod)

# Calculate the dropped percentage by franchise
dropped_percentage_by_franchise = total_rows_by_franchise.sub(total_rows_by_franchise_mod) / total_rows_by_franchise * 100

# Calculate the percentage of dropped data
dropped_percentage = ((total_rows - remaining_rows) / total_rows) * 100
print("Percentage of dropped data: {:.2f}%".format(dropped_percentage))

# Create a dataframe storing the data retention results
data_retention = pd.concat([total_rows_by_franchise, total_rows_by_franchise_mod,
                           dropped_rows_by_franchise, dropped_percentage_by_franchise],
                          axis=1)
data_retention = data_retention.reset_index(drop=False)
data_retention = data_retention.rename(columns = {0: 'row_count_original', 1: 'row_count_cleaned', 2: 'dropped_row_count', 3: 'data_lost_percentage'})
data_retention

Percentage of dropped data: 28.26%

,franchise_name,row_count_original,row_count_cleaned,dropped_row_count,data_lost_percentage
0,イトーヨーカドー,93,93,0,0.00
1,トモズ,912,640,272,29.82
2,マツモトキヨシ,3401,2428,973,28.61

In [18]:
# Convert invoice_date column to datetime type
invoice_data['invoice_date'] = pd.to_datetime(invoice_data['invoice_date'], errors='coerce')

# Drop rows with non-date data in invoice_date column
invoice_data = invoice_data.dropna(subset=['invoice_date'])

# Extract calendar month and year from invoice_date
invoice_data['calendar_month'] = invoice_data['invoice_date'].dt.month
invoice_data['calendar_year'] = invoice_data['invoice_date'].dt.year

# Calculate annual sales for each row
invoice_data['total_sales'] = invoice_data['product1_sales'] + invoice_data['product2_sales'] + invoice_data['product3_sales']

# Calculate monthly sales for each franchise and year
monthly_sales = invoice_data.groupby(['franchise_name', 'calendar_year', 'calendar_month'])['total_sales'].sum()

# Calculate annual sales for each franchise and year
annual_sales = invoice_data.groupby(['franchise_name', 'calendar_year'])['total_sales'].sum()

# Calculate the number of invoices and average sales per invoice for each month
invoice_number = invoice_data.groupby(['franchise_name', 'calendar_year', 'calendar_month'])['invoice_date'].count()
invoice_avg = monthly_sales / invoice_number

# Create a new DataFrame for sales by franchise, year, and month
sales_by_franchise_year_month_df = pd.DataFrame({
    'Franchise Name': monthly_sales.index.get_level_values('franchise_name'),
    'Year': monthly_sales.index.get_level_values('calendar_year'),
    'Month': monthly_sales.index.get_level_values('calendar_month'),
    'Sales': monthly_sales.values,
    'Invoice Number': invoice_number.values,
    'Invoice Avg': invoice_avg.values
})

# Create a new DataFrame for sales by franchise and year
sales_by_franchise_year_df = pd.DataFrame({
    'Franchise Name': annual_sales.index.get_level_values('franchise_name'),
    'Year': annual_sales.index.get_level_values('calendar_year'),
    'Sales': annual_sales.values,
    'Invoice Number': '',
    'Invoice Avg': ''
})

# Calculate the number of invoices and average sales per invoice for each year
yearly_invoice_number = invoice_data.groupby(['franchise_name', 'calendar_year'])['invoice_date'].count()
yearly_invoice_avg = annual_sales / yearly_invoice_number

# Update the "Invoice Number" and "Invoice Avg" columns in the sales_by_franchise_year_df DataFrame
sales_by_franchise_year_df['Invoice Number'] = yearly_invoice_number.values
sales_by_franchise_year_df['Invoice Avg'] = yearly_invoice_avg.values

# Add the "total" row to the DataFrame for sales by franchise, year, and month
sales_by_franchise_year_month_df.loc[len(sales_by_franchise_year_month_df)] = ['Total', '', '',
                                                                              sales_by_franchise_year_month_df['Sales'].sum(),
                                                                              sales_by_franchise_year_month_df['Invoice Number'].sum(),
                                                                              sales_by_franchise_year_month_df['Sales'].sum() / sales_by_franchise_year_month_df['Invoice Number'].sum()]

# Add the "total" row to the DataFrame for sales by franchise and year
sales_by_franchise_year_df.loc[len(sales_by_franchise_year_df)] = ['Total', '',
                                                                  sales_by_franchise_year_df['Sales'].sum(),
                                                                  sales_by_franchise_year_df['Invoice Number'].sum(),
                                                                  sales_by_franchise_year_df['Sales'].sum() / sales_by_franchise_year_df['Invoice Number'].sum()]

# Reset the index of the DataFrames
sales_by_franchise_year_month_df = sales_by_franchise_year_month_df.reset_index(drop=True)
sales_by_franchise_year_df = sales_by_franchise_year_df.reset_index(drop=True)

# Print the sales by franchise, year, and month DataFrame
print("Sales by Franchise, Year, and Month:")
print(sales_by_franchise_year_month_df)
print()

# Print the sales by franchise and year DataFrame
print("Sales by Franchise and Year:")
print(sales_by_franchise_year_df)

Sales by Franchise, Year, and Month:
   Franchise Name  Year Month         Sales  Invoice Number  Invoice Avg
0        イトーヨーカドー  2020     1    2200000.00               4    550000.00
1        イトーヨーカドー  2020     2     550000.00               1    550000.00
2        イトーヨーカドー  2020     3    1100000.00               2    550000.00
3        イトーヨーカドー  2020     4    2200000.00               4    550000.00
4        イトーヨーカドー  2020     5     550000.00               1    550000.00
..            ...   ...   ...           ...             ...          ...
92        マツモトキヨシ  2023     1   53150000.00              88    603977.27
93        マツモトキヨシ  2023     2   53000000.00              90    588888.89
94        マツモトキヨシ  2023     3   52100000.00              82    635365.85
95        マツモトキヨシ  2023     4   53150000.00              88    603977.27
96          Total             1968050000.00            3161    622603.61

[97 rows x 6 columns]

Sales by Franchise and Year:
   Franchise Name  Year         Sales  Invoice Number  Invoice Avg
0        イトーヨーカドー  2020   14300000.00              26    550000.00
1        イトーヨーカドー  2021   15400000.00              28    550000.00
2        イトーヨーカドー  2022   15400000.00              28    550000.00
3        イトーヨーカドー  2023    6050000.00              11    550000.00
4             トモズ  2021  189800000.00             276    687681.16
5             トモズ  2022  189800000.00             276    687681.16
6             トモズ  2023   59900000.00              88    680681.82
7         マツモトキヨシ  2021  633000000.00            1040    608653.85
8         マツモトキヨシ  2022  633000000.00            1040    608653.85
9         マツモトキヨシ  2023  211400000.00             348    607471.26
10          Total       1968050000.00            3161    622603.61

<ipython-input-18-9346b769f20b>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  invoice_data['calendar_month'] = invoice_data['invoice_date'].dt.month
<ipython-input-18-9346b769f20b>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  invoice_data['calendar_year'] = invoice_data['invoice_date'].dt.year
<ipython-input-18-9346b769f20b>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  invoice_data['total_sales'] = invoice_data['product1_sales'] + invoice_data['product2_sales'] + invoice_data['product3_sales']

In [19]:
# Print the sales by franchise, year, and month DataFrame
sales_by_franchise_year_month_df

   Franchise Name  Year Month         Sales  Invoice Number  Invoice Avg
0        イトーヨーカドー  2020     1    2200000.00               4    550000.00
1        イトーヨーカドー  2020     2     550000.00               1    550000.00
2        イトーヨーカドー  2020     3    1100000.00               2    550000.00
3        イトーヨーカドー  2020     4    2200000.00               4    550000.00
4        イトーヨーカドー  2020     5     550000.00               1    550000.00
..            ...   ...   ...           ...             ...          ...
92        マツモトキヨシ  2023     1   53150000.00              88    603977.27
93        マツモトキヨシ  2023     2   53000000.00              90    588888.89
94        マツモトキヨシ  2023     3   52100000.00              82    635365.85
95        マツモトキヨシ  2023     4   53150000.00              88    603977.27
96          Total             1968050000.00            3161    622603.61

[97 rows x 6 columns]

In [20]:
# Print the sales by franchise and year DataFrame
sales_by_franchise_year_df

   Franchise Name  Year         Sales  Invoice Number  Invoice Avg
0        イトーヨーカドー  2020   14300000.00              26    550000.00
1        イトーヨーカドー  2021   15400000.00              28    550000.00
2        イトーヨーカドー  2022   15400000.00              28    550000.00
3        イトーヨーカドー  2023    6050000.00              11    550000.00
4             トモズ  2021  189800000.00             276    687681.16
5             トモズ  2022  189800000.00             276    687681.16
6             トモズ  2023   59900000.00              88    680681.82
7         マツモトキヨシ  2021  633000000.00            1040    608653.85
8         マツモトキヨシ  2022  633000000.00            1040    608653.85
9         マツモトキヨシ  2023  211400000.00             348    607471.26
10          Total       1968050000.00            3161    622603.61

In [22]:
# Check the updated Dataset
#invoice_data
invoice_data.columns

Index(['file_name', 'store_name', 'invoice_number', 'invoice_date',
       'product_1', 'quantity_1', 'product_2', 'quantity_2', 'product_3',
       'quantity_3', 'company_name', 'franchise_name', 'company_store',
       'address', 'prefecture', 'municipality', 'product1_sales',
       'product2_sales', 'product3_sales', 'calendar_month', 'calendar_year',
       'total_sales'],
      dtype='object')

# Profitability Analysis

In [122]:
invoice_data = pd.read_excel('/content/drive/MyDrive/EY Recruitment Documents/invoice_data_master.xlsx')
invoice_data = invoice_data.fillna(0)
#invoice_data.head(1)

In [124]:
# Product prices
product_prices = {
    'メンズ・シャンプーM': 2500,
    'レディース・シャンプーL': 3000,
    'ラグジュアリ・シャンプーEx': 5000
}

# Calculate total sales for each product
invoice_data['product1_sales'] = invoice_data['quantity_1'] * product_prices['メンズ・シャンプーM']
invoice_data['product2_sales'] = invoice_data['quantity_2'] * product_prices['レディース・シャンプーL']
invoice_data['product3_sales'] = invoice_data['quantity_3'] * product_prices['ラグジュアリ・シャンプーEx']
#invoice_data.head(1)

In [125]:
# Product Cost
product_cost = {
    'メンズ・シャンプーM': 800,
    'レディース・シャンプーL': 800,
    'ラグジュアリ・シャンプーEx': 1000
}

# Calcualte the total cost per row
invoice_data['product1_cost'] = invoice_data['quantity_1'] * product_cost['メンズ・シャンプーM']
invoice_data['product2_cost'] = invoice_data['quantity_2'] * product_cost['レディース・シャンプーL']
invoice_data['product3_cost'] = invoice_data['quantity_3'] * product_cost['ラグジュアリ・シャンプーEx']
#invoice_data.head(1)

In [126]:
# Calculate total sales and total cost
invoice_data['total_sales'] = invoice_data['product1_sales'] + invoice_data['product2_sales'] + invoice_data['product3_sales']
invoice_data['total_cost'] = invoice_data['product1_cost'] + invoice_data['product2_cost'] + invoice_data['product3_cost']

# Calculate profitability
invoice_data['profitability'] = (invoice_data['total_sales'] - invoice_data['total_cost']) / invoice_data['total_sales']

# Print the updated DataFrame
invoice_data.head(1)#['profitability'].unique()

,file_name,store_name,invoice_number,invoice_date,product_1,quantity_1,product_2,quantity_2,product_3,quantity_3,...,municipality,product1_sales,product2_sales,product3_sales,product1_cost,product2_cost,product3_cost,total_sales,total_cost,profitability
0,202009000096221.xlsx,お花茶屋店,202009000096221,44091,メンズ・シャンプーM,100,レディース・シャンプーL,100,0,0.00,...,東京都葛飾区,250000,300000,0.00,80000,80000,0.00,550000.00,160000.00,0.71

In [127]:
# Calculate total sales and total cost
invoice_data['total_sales'] = invoice_data['product1_sales'] + invoice_data['product2_sales'] + invoice_data['product3_sales']
invoice_data['total_cost'] = invoice_data['product1_cost'] + invoice_data['product2_cost'] + invoice_data['product3_cost']

# Calculate profitability
invoice_data['profitability'] = (invoice_data['total_sales'] - invoice_data['total_cost']) / invoice_data['total_sales']

# Convert invoice_date column to datetime type
invoice_data['invoice_date'] = pd.to_datetime(invoice_data['invoice_date'], errors='coerce')

# Drop rows with non-date data in invoice_date column
invoice_data = invoice_data.dropna(subset=['invoice_date'])

# Calculate profitability per franchise
profitability_per_franchise = invoice_data.groupby('franchise_name')['profitability'].mean()

# Calculate monthly profitability per franchise
invoice_data['invoice_month'] = invoice_data['invoice_date'].dt.month
invoice_data['invoice_year'] = invoice_data['invoice_date'].dt.year
monthly_profitability = invoice_data.groupby(['franchise_name', 'invoice_year', 'invoice_month'])['profitability'].mean().reset_index()
monthly_profitability.columns = ['Franchise Name', 'Year', 'Month', 'Profitability']

# Calculate yearly profitability per franchise
yearly_profitability = invoice_data.groupby(['franchise_name', 'invoice_year'])['profitability'].mean().reset_index()
yearly_profitability.columns = ['Franchise Name', 'Year', 'Profitability']

<ipython-input-127-b122588cba19>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  invoice_data['invoice_month'] = invoice_data['invoice_date'].dt.month
<ipython-input-127-b122588cba19>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  invoice_data['invoice_year'] = invoice_data['invoice_date'].dt.year

In [128]:
# Create a new DataFrame for profitability per franchise
profitability_df = pd.DataFrame(profitability_per_franchise).reset_index()
profitability_df.columns = ['Franchise Name', 'Profitability']
profitability_df#['Profitability'].unique()

  Franchise Name  Profitability
0       イトーヨーカドー           0.71
1            トモズ           0.72
2        マツモトキヨシ           0.71

In [129]:
# Print the monthly profitability per franchise DataFrame
print("Monthly Profitability per Franchise:")
#monthly_profitability#['Profitability'].unique()

Monthly Profitability per Franchise:

In [130]:
# Print the yearly profitability per franchise DataFrame
print("Yearly Profitability per Franchise:")
yearly_profitability['Profitability'].unique()

Yearly Profitability per Franchise:

array([0.70909091, 0.7227759 , 0.7222501 , 0.71492362, 0.71480538])

## Reasons for no profit margin difference
- The order quantitity of the products is probably similar across all franshise, hence not making any major differene in the profit margins
- The company is likley have a inflexible ordering system which results in similar orderquanitity per store across all franchsises
    * メンズ・シャンプーM & レディース・シャンプーL only accepts batch order of 100
    * ラグジュアリ・シャンプーEx accepts batch order of 50 or 100

In [136]:
# Convert invoice_date column to datetime type
invoice_data['invoice_date'] = pd.to_datetime(invoice_data['invoice_date'], errors='coerce')

# Calculate average product quantity by franchise
avg_quantity = invoice_data.groupby(['franchise_name'])['quantity_1', 'quantity_2', 'quantity_3'].mean().reset_index()
avg_quantity.columns = ['Franchise Name', 'Avg_Quantity_1', 'Avg_Quantity_2', 'Avg_Quantity_3']

# Calculate average product quantity per month and year by franchise
avg_quantity_per_month = invoice_data.groupby(['franchise_name', 'invoice_year', 'invoice_month'])['quantity_1', 'quantity_2', 'quantity_3'].mean().reset_index()
avg_quantity_per_month.columns = ['Franchise Name', 'Year', 'Month', 'Avg_Quantity_1', 'Avg_Quantity_2', 'Avg_Quantity_3']

# Calculate average product quantity per year by franchise
avg_quantity_per_year = invoice_data.groupby(['franchise_name', 'invoice_year'])['quantity_1', 'quantity_2', 'quantity_3'].mean().reset_index()
avg_quantity_per_year.columns = ['Franchise Name', 'Year', 'Avg_Quantity_1', 'Avg_Quantity_2', 'Avg_Quantity_3']

<ipython-input-136-51df45bb81e5>:5: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  avg_quantity = invoice_data.groupby(['franchise_name'])['quantity_1', 'quantity_2', 'quantity_3'].mean().reset_index()
<ipython-input-136-51df45bb81e5>:9: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  avg_quantity_per_month = invoice_data.groupby(['franchise_name', 'invoice_year', 'invoice_month'])['quantity_1', 'quantity_2', 'quantity_3'].mean().reset_index()
<ipython-input-136-51df45bb81e5>:13: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  avg_quantity_per_year = invoice_data.groupby(['franchise_name', 'invoice_year'])['quantity_1', 'quantity_2', 'quantity_3'].mean().reset_index()

In [137]:
# Print the average product quantity DataFrame
print("Average Product Quantity by Franchise:")
avg_quantity

Average Product Quantity by Franchise:

  Franchise Name  Avg_Quantity_1  Avg_Quantity_2  Avg_Quantity_3
0       イトーヨーカドー          100.00          100.00            0.00
1            トモズ          100.00          100.00           27.34
2        マツモトキヨシ          100.00          100.00           11.70

In [132]:
# Print the average product quantity per month DataFrame
print("Average Product Quantity per Month by Franchise:")
avg_quantity_per_month

Average Product Quantity per Month by Franchise:

   Franchise Name  Year  Month  Avg_Quantity_1  Avg_Quantity_2  Avg_Quantity_3
0        イトーヨーカドー  2020      1          100.00          100.00            0.00
1        イトーヨーカドー  2020      2          100.00          100.00            0.00
2        イトーヨーカドー  2020      3          100.00          100.00            0.00
3        イトーヨーカドー  2020      4          100.00          100.00            0.00
4        イトーヨーカドー  2020      5          100.00          100.00            0.00
..            ...   ...    ...             ...             ...             ...
91        マツモトキヨシ  2022     12          100.00          100.00           17.07
92        マツモトキヨシ  2023      1          100.00          100.00           10.80
93        マツモトキヨシ  2023      2          100.00          100.00            7.78
94        マツモトキヨシ  2023      3          100.00          100.00           17.07
95        マツモトキヨシ  2023      4          100.00          100.00           10.80

[96 rows x 6 columns]

In [133]:
# Print the average product quantity per year DataFrame
print("Average Product Quantity per Year by Franchise:")
avg_quantity_per_year

Average Product Quantity per Year by Franchise:

  Franchise Name  Year  Avg_Quantity_1  Avg_Quantity_2  Avg_Quantity_3
0       イトーヨーカドー  2020          100.00          100.00            0.00
1       イトーヨーカドー  2021          100.00          100.00            0.00
2       イトーヨーカドー  2022          100.00          100.00            0.00
3       イトーヨーカドー  2023          100.00          100.00            0.00
4            トモズ  2021          100.00          100.00           27.54
5            トモズ  2022          100.00          100.00           27.54
6            トモズ  2023          100.00          100.00           26.14
7        マツモトキヨシ  2021          100.00          100.00           11.73
8        マツモトキヨシ  2022          100.00          100.00           11.73
9        マツモトキヨシ  2023          100.00          100.00           11.49

In [150]:
# Check the variables in メンズ・シャンプーM order quantity per invoice
invoice_data['quantity_1'].unique()

array([100])

In [151]:
# Check the variables in レディース・シャンプーL order quantity per invoice
invoice_data['quantity_2'].unique()

array([100])

In [152]:
# Check the variables in ラグジュアリ・シャンプーEx order quantity per invoice
invoice_data['quantity_3'].unique()

array([  0., 100.,  50.])

# Check Product Availability rate by each Franchise
- This analysis will only target the Kanto region (一都三県): Tokyo, Kanagawa, Chiba, Saitama per client request

## Donwload the store info dataset and extract prefecture information

In [184]:
# Use the store info dataset created via eb scraping
store_info = pd.read_excel('/content/drive/MyDrive/EY Recruitment Documents/franchise_info/store_info_all.xlsx')
#store_info

In [185]:
# Download package
import re

# Define regular expressions for extracting prefecture and municipal strings
prefecture_regex = r'([一-龥]+都|[一-龥]+府|[一-龥]+県|[一-龥]+道)'
municipality_regex = r'([一-龥]+市|[一-龥]+区|[一-龥]+町|[一-龥]+村)'

# Function to extract prefecture string from address
def extract_prefecture(address):
    match = re.search(prefecture_regex, address)
    return match.group(0) if match else None

# Apply function to extract prefecture information and create new column
store_info['prefecture'] = store_info['store_address'].apply(extract_prefecture)

# Display the DataFrame
store_info

,store_name,store_hours,store_address,franchise_name,prefecture
0,薬局トモズ 成城コルティ店,営業時間外 - 営業開始時間 9:00,東京都世田谷区成城6-5-34 成城コルティ 3F,トモズ,東京都
1,トモズ 白金高輪店,営業時間外 - 営業開始時間 9:00,東京都港区高輪 1丁目3-1 プレミストタワー白金高輪 1F,トモズ,東京都
2,トモズ アークヒルズ店,営業時間外 - 営業開始時間 8:30,東京都港区赤坂1-12-32アーク森ビル 2F,トモズ,東京都
3,トモズ 青葉台店,営業時間外 - 営業開始時間 9:00,神奈川県横浜市青葉区青葉台1-6-14エキニア青葉台,トモズ,神奈川県
4,トモズ 青葉台東急スクエア店,営業時間外 - 営業開始時間 10:00,神奈川県横浜市青葉区青葉台2-1-1青葉台東急スクエアNorth-1 1·2F,トモズ,神奈川県
...,...,...,...,...,...
1832,マツモトキヨシハンビータウン店,NaN,沖縄県中頭郡北谷町北前１-２-３,マツモトキヨシ,沖縄県
1833,マツモトキヨシ北谷はまがわ店,NaN,沖縄県中頭郡北谷町字宮城１-３７,マツモトキヨシ,沖縄県
1834,マツモトキヨシなかぐすく店,NaN,沖縄県中頭郡中城村字南上原７９５,マツモトキヨシ,沖縄県
1835,マツモトキヨシ板良敷店,NaN,沖縄県島尻郡与那原町字板良敷６２１番地,マツモトキヨシ,沖縄県
1836,マツモトキヨシ八重瀬シティ店,NaN,沖縄県島尻郡八重瀬町字屋宜原９９-１,マツモトキヨシ,沖縄県

In [186]:
store_info['prefecture'].unique()

array(['東京都', '神奈川県', '埼玉県', '千葉県', '宮城県', '青森県', '福島県', '北海道', '静岡県',
       '兵庫県加古川市別府', '岩手県', '愛知県', '長野県', '茨城県', '山梨県', '岐阜県', '大阪府',
       '兵庫県', '栃木県宇都', '神奈川県横浜市都', '新潟県', '秋田県', '山形県', '栃木県', '栃木県下都',
       '群馬県', '富山県', '石川県', '福井県', '山梨県甲府', '山梨県都', '山梨県南都', '愛知県大府',
       '三重県', '滋賀県', '京都府京都', '京都', '大阪府大阪市都', '奈良県', '和歌山県', '鳥取県',
       '島根県', '岡山県', '広島県', '山口県', '徳島県', '香川県', '愛媛県', '高知県', '福岡県',
       '佐賀県', '長崎県', '熊本県', '大分県', '宮崎県', '宮崎県都', '宮崎県北諸県', '鹿児島県', '沖縄県'],
      dtype=object)

In [190]:
# Curate a dataset that only contains stores in Tokyo, Kanagawa, Saitama, and Chiba
store_info_mod = store_info.loc[store_info['prefecture'].isin(['東京都', '神奈川県', '埼玉県', '千葉県'])]
print(store_info_mod['prefecture'].unique())
store_info_mod

['東京都' '神奈川県' '埼玉県' '千葉県']

,store_name,store_hours,store_address,franchise_name,prefecture
0,薬局トモズ 成城コルティ店,営業時間外 - 営業開始時間 9:00,東京都世田谷区成城6-5-34 成城コルティ 3F,トモズ,東京都
1,トモズ 白金高輪店,営業時間外 - 営業開始時間 9:00,東京都港区高輪 1丁目3-1 プレミストタワー白金高輪 1F,トモズ,東京都
2,トモズ アークヒルズ店,営業時間外 - 営業開始時間 8:30,東京都港区赤坂1-12-32アーク森ビル 2F,トモズ,東京都
3,トモズ 青葉台店,営業時間外 - 営業開始時間 9:00,神奈川県横浜市青葉区青葉台1-6-14エキニア青葉台,トモズ,神奈川県
4,トモズ 青葉台東急スクエア店,営業時間外 - 営業開始時間 10:00,神奈川県横浜市青葉区青葉台2-1-1青葉台東急スクエアNorth-1 1·2F,トモズ,神奈川県
...,...,...,...,...,...
1238,全国のマツモトキヨシ一覧,NaN,神奈川県海老名市中央１-６-１,マツモトキヨシ,神奈川県
1239,マツモトキヨシマルイファミリー海老名店,NaN,神奈川県海老名市中央１-６-１,マツモトキヨシ,神奈川県
1240,マツモトキヨシさがみ野店,NaN,神奈川県海老名市東柏ヶ谷５-１４-６,マツモトキヨシ,神奈川県
1241,マツモトキヨシ小田急マルシェ相武台店,NaN,神奈川県座間市相武台１-３３-２,マツモトキヨシ,神奈川県
1242,マツモトキヨシコピオ愛川店,NaN,神奈川県愛甲郡愛川町角田字小沢下原５８０,マツモトキヨシ,神奈川県

## Clean the prefecture information in the invoice dataset

In [197]:
# Download a fresh dataset since the previous version dropped rows without a proper invoice date
invoice_data = pd.read_excel('/content/drive/MyDrive/EY Recruitment Documents/invoice_data_master.xlsx')
invoice_data = invoice_data.fillna(0)
#invoice_data

In [198]:
# Check whether the prefecture column contains unexpected values
invoice_data['prefecture'].unique()

array(['東京都', '神奈川県', '埼玉県', '千葉県', '神奈川県横浜市都', '埼玉県東松山市東松山都'],
      dtype=object)

In [200]:
# Manually replace the unexpected values
invoice_data['prefecture'] = invoice_data['prefecture'].replace({'神奈川県横浜市都':'神奈川県', '埼玉県東松山市東松山都':'埼玉県'})
invoice_data['prefecture'].unique()
#invoice_data.head()

array(['東京都', '神奈川県', '埼玉県', '千葉県'], dtype=object)

## Calculate how many stores are in each prefecture and how many of them sells the product

### Store Data

In [208]:
# Create a DataFrame with all possible combinations of franchises and prefectures
franchises = store_info_mod['franchise_name'].unique()
prefectures = store_info_mod['prefecture'].unique()
all_combinations = pd.MultiIndex.from_product([franchises, prefectures], names=['franchise_name', 'prefecture'])
all_combinations_df = pd.DataFrame(index=all_combinations).reset_index()

# Calculate the number of stores per franchise and prefecture
stores_per_franchise = store_info_mod.groupby(['franchise_name', 'prefecture']).size().reset_index(name='store_count')

# Perform a left join to include franchises without stores in a prefecture
total_stores = pd.merge(all_combinations_df, stores_per_franchise, on=['franchise_name', 'prefecture'], how='left')
total_stores['store_count'].fillna(0, inplace=True)

# Display the resulting dataset
total_stores

   franchise_name prefecture  store_count
0             トモズ        東京都          145
1             トモズ       神奈川県           51
2             トモズ        埼玉県           20
3             トモズ        千葉県            7
4        イトーヨーカドー        東京都           27
5        イトーヨーカドー       神奈川県           28
6        イトーヨーカドー        埼玉県           19
7        イトーヨーカドー        千葉県           16
8         マツモトキヨシ        東京都          241
9         マツモトキヨシ       神奈川県           93
10        マツモトキヨシ        埼玉県          138
11        マツモトキヨシ        千葉県          210

### Invoice Data

In [218]:
# Group the data by 'franchise_name' and 'prefecture', and count the unique 'store_name' values
available_stores = df.groupby(['franchise_name', 'prefecture'])['store_name'].nunique().reset_index()

# Rename the column to 'store_count'
available_stores.rename(columns={'store_name': 'store_available'}, inplace=True)

# Print the resulting data frame
available_stores

   franchise_name prefecture  store_available
0        イトーヨーカドー        千葉県                2
1        イトーヨーカドー        埼玉県                1
2        イトーヨーカドー        東京都                3
3        イトーヨーカドー       神奈川県                1
4             トモズ        千葉県                4
5             トモズ        埼玉県                6
6             トモズ        東京都               47
7             トモズ       神奈川県               12
8         マツモトキヨシ        千葉県               66
9         マツモトキヨシ        埼玉県               61
10        マツモトキヨシ        東京都               93
11        マツモトキヨシ       神奈川県               39

### Merge the Results

In [219]:
# Create a column to merge on
total_stores['merge'] = total_stores['franchise_name'] + total_stores['prefecture']
available_stores['merge'] = available_stores['franchise_name'] + available_stores['prefecture']

In [224]:
# Merge the datset and create availbility columns
product_availability = pd.merge(available_stores, total_stores[['store_count', 'merge']], on='merge')
product_availability = product_availability.drop(columns = 'merge')
product_availability['availability'] = product_availability['store_available'] / product_availability['store_count']
product_availability

   franchise_name prefecture  store_available  store_count  availability
0        イトーヨーカドー        千葉県                2           16          0.12
1        イトーヨーカドー        埼玉県                1           19          0.05
2        イトーヨーカドー        東京都                3           27          0.11
3        イトーヨーカドー       神奈川県                1           28          0.04
4             トモズ        千葉県                4            7          0.57
5             トモズ        埼玉県                6           20          0.30
6             トモズ        東京都               47          145          0.32
7             トモズ       神奈川県               12           51          0.24
8         マツモトキヨシ        千葉県               66          210          0.31
9         マツモトキヨシ        埼玉県               61          138          0.44
10        マツモトキヨシ        東京都               93          241          0.39
11        マツモトキヨシ       神奈川県               39           93          0.42